name: Script Excecution With Planarity Check
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Execute and Check Planarity of Demo Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install sagemath
      - run: sage assessment-task-server/graph_assessment.py -task PLANARITY -file assessment-task-server/resources/graph.json